### PR TITLE
18 independent testing of fmt cir

### PR DESCRIPTION
**Pull request by burlave**

### CODE REVIEW

**Comment by elong0527** [comment]
> Hi @burlave , please re-submit your PR from branch #18 to branch #41.

Just curious, What's the reason for that?

**Comment by LittleBeannie** [comment]
> > Hi @burlave , please re-submit your PR from branch #18 to branch #41.
> 
> Just curious, What's the reason for that?

Oh, because last time when I test `gsdmvn`, there were some PR revoked and caused mass/conflicts in the `master`. So this time, I am more conservative: merge all tests to #41 test branch, and when #41 is mature, merge it to the `master`.

**Comment by elong0527** [comment]
Let's avoid this strategy. It should always merge into the master branch instead of holding a large development branch.

**Comment by nanxstats** [comment]
I agree with @elong0527 . Let's try minimize the chance of creating a complex branching model or keeping large unmerged branches. Here is some reasoning from _Software Engineering at Google_, Chapter 16, on branch management:

(Here, "trunk" means the main branch)

> We believe that a version control policy that makes extensive use of dev branches as a means toward product stability is inherently misguided. The same set of commits are going to be merged to trunk eventually. Small merges are easier than big ones. Merges done by the engineer who authored those changes are easier than batching unrelated changes and merging later (which will happen eventually if a team is sharing a dev branch).

> Beyond the lack of expertise and inherent problems in merging a single branch, there are significant scaling risks when relying on dev branches. This is a very common productivity drain for a software organization. When there are multiple branches being developed in isolation for long periods, coordinating merge operations becomes significantly more expensive (and possibly riskier) than they would be with trunk-based development.

> All of that effort in merging and retesting is pure overhead. The alternative requires a different paradigm: trunk-based development, rely heavily on testing and CI, keep the build green, and disable incomplete/untested features at runtime.

**Comment by BrianLang** [comment]
Do you guys have a recommendation as to how to avoid what Yujie described while sticking to the “one main branch” approach? 
I’m not sure I fully understand the issue that occurred, there was a problem with a past commit  and we needed a rebase?

**Pull request merged**
