### PR TITLE
37 independent snapshot testing for tlf ae specificr

### PR DESCRIPTION
**Pull request by howardbaek**
Snapshot testing for `tlf_ae_specific()`. All tests passed

### CODE REVIEW

**Comment by elong0527** [comment]
Please follow the update in #73 to pass code coverage test.

**Comment by howardbaek** [comment]
Do you know why we keep on getting `Rplots.pdf` when we run tests for `tlf_ae_summary()` and `tlf_ae_specific()`?

**Comment by LittleBeannie** [comment]
> Rplots.pdf

I am not sure if this is helpful or not. An answer from google: https://stackoverflow.com/questions/6535927/how-do-i-prevent-rplots-pdf-from-being-generated

**Comment by howardbaek** [comment]
> > Do you know why we keep on getting `Rplots.pdf` when we run tests for `tlf_ae_summary()` and `tlf_ae_specific()`?
> 
> please remove it. That is a default behavior when you have a graph device open. But not sure how to avoid that~

The SO post suggested including `pdf(NULL)`, so I included this at the top of my testing script, and it seems to have solved the problem.

**Comment by elong0527** [comment]
> > > Do you know why we keep on getting `Rplots.pdf` when we run tests for `tlf_ae_summary()` and `tlf_ae_specific()`?
> > 
> > 
> > please remove it. That is a default behavior when you have a graph device open. But not sure how to avoid that~
> 
> The SO [post ](https://stackoverflow.com/questions/6535927/how-do-i-prevent-rplots-pdf-from-being-generated)suggested including `pdf(NULL)`, so I included this at the top of my testing script, and it seems to have solved the problem.

Cool, my solution is to update .gitignore to avoid unnecessary files.

**Comment by fb-elong** [comment]
Let me commit a few changes to reduce the commit size and pass the test.

**Comment by fb-elong** [comment]
I guess the change in #77 is sufficient to pass the test.

**Comment by elong0527** [comment]
Fixed the testing in #78. To enhance robustness, let's snapshot `tbl` instead of the `rtf` file.

**Comment by howardbaek** [comment]
Got it. Thanks for the help @elong0527

**Comment by BrianLang** [comment]
> Fixed the testing in #78. To enhance robustness, let's snapshot `tbl` instead of the `rtf` file. 

This is an approach that is quite dangerous, tlf_ae_specific doesn't process the tbl enough to make this test meaningful. This is probably why we missed the tlf_ae_specific was still needing half of its development.

**Pull request closed without merging**
