### PR TITLE
First commit: Supports only Treatment Within subgroup Analysis.

### PR DESCRIPTION
**Pull request by ruchitpatel2002**
Need update:
 - Automatic update of title based on user input. Either "trt_within_sub" or "sub_within_trt".
 - Number of treatment groups to be displayed on each page. @elong0527 Is there an functionality available in r2rtf?
 - "sub_within_trt" functional programming is pending.

### CODE REVIEW

**Comment by BrianLang** [comment]
Hi Ruchit, can you tell us what you need from us in terms of this PR? Was there a nice spec that you followed for this work that we can use to assess your implementation?
Cheers
B

**Comment by nanxstats** [comment]
Is this still being worked on? @LittleBeannie @elong0527

**Comment by LittleBeannie** [comment]
> Is this still being worked on? @LittleBeannie @elong0527

Yes

**Comment by wangben718** [comment]
Close this and try it in another PR

**Pull request closed without merging**
